# Generated by Django 2.0.6 on 2018-06-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_icon',
            field=models.ImageField(blank=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
